<?php

/**
 * @file
 * Contains pickup_game.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pickup_game_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pickup_game module.
    case 'help.page.pickup_game':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Handles configuration and theming of pickup games') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function pickup_game_theme() {
  $theme = [];

  return $theme;
}

/**
 * Implements hook_preprocess_node().
 */
function pickup_game_preprocess_node(&$variables) {
  //dpm('$variables');
}
